"""Add paypal_order_id to Order model

Revision ID: 9fce5dad2f4c
Revises: fd7bfc7c2d4b
Create Date: 2025-08-24 22:07:37.024340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fce5dad2f4c'
down_revision = 'fd7bfc7c2d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_order_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('paypal_order_id')

    # ### end Alembic commands ###
